#!/usr/bin/env python3
"""Master Controller (The CEO) — real pipeline, no mocks.

Loops through every active channel in channels/database.json, finds a real
trending topic, builds a real narrated+subtitled video from free stock
footage, and uploads it to the real YouTube channel via OAuth2.

Env vars:
  SKIP_UPLOAD=1          Build videos without uploading to YouTube (testing).
  TARGET_MINUTES=8       Narration length target per video.
  ONLY_CHANNEL=<id>      Process just this one channel (used by the
                         Telegram bot's "make a video now" / "test channel"
                         commands so the user doesn't have to wait for
                         every channel to render before seeing a result).
  DELIVER_MODE=telegram|release|both   How to hand the finished MP4 to the
                         user (default: both — Telegram if it fits under
                         the Bot API's ~50MB upload limit, else a GitHub
                         Release download link; 'both' tries Telegram first
                         and always ALSO publishes a Release link as a
                         permanent backup/archive).
"""

import os
import json
import sys

from core.niche_analyzer import NicheAnalyzer
from core.video_factory import VideoFactory
from core.auto_publisher import AutoPublisher
from core.performance_analyzer import PerformanceAnalyzer
from core.gh_release import GitHubRelease
from core import telegram_notify

_DB_PATH = "channels/database.json"
_TELEGRAM_FILE_LIMIT = 49 * 1024 * 1024  # Bot API hard cap is 50MB; stay safely under it


def load_channels() -> list:
    if not os.path.exists(_DB_PATH):
        print(f"❌ {_DB_PATH} not found. Run core/channel_spawner.py first to register a channel.")
        return []
    with open(_DB_PATH) as f:
        return json.load(f).get("channels", [])


def _deliver_video(video_path: str, channel_name: str, topic: str, mode: str) -> str:
    """Sends/uploads the finished video per DELIVER_MODE and returns a
    human-readable string describing where to find it (used in the Telegram
    summary message and the console log)."""
    size = os.path.getsize(video_path) if os.path.exists(video_path) else 0
    lines = []

    sent_via_telegram = False
    if mode in ("telegram", "both") and size and size <= _TELEGRAM_FILE_LIMIT:
        import requests
        token = os.environ.get("TELEGRAM_BOT_TOKEN_FACTORY", "")
        chat_id = telegram_notify._chat_id()
        if token and chat_id:
            try:
                with open(video_path, "rb") as f:
                    r = requests.post(
                        f"https://api.telegram.org/bot{token}/sendVideo",
                        data={"chat_id": chat_id, "caption": f"🎬 {channel_name}: {topic}"[:1000]},
                        files={"video": f},
                        timeout=180,
                    )
                if r.json().get("ok"):
                    sent_via_telegram = True
                    lines.append("📲 مستقیم توی تلگرام ارسال شد")
                else:
                    print(f"[deliver] Telegram sendVideo failed: {r.text[:300]}")
            except Exception as e:
                print(f"[deliver] Telegram sendVideo error: {e}")
        else:
            print("[deliver] Telegram not configured (TELEGRAM_BOT_TOKEN_FACTORY / chat id missing)")
    elif mode in ("telegram", "both") and size > _TELEGRAM_FILE_LIMIT:
        lines.append(f"📦 حجم فایل ({size / 1e6:.0f}MB) برای تلگرام زیاده — از لینک گیت‌هاب استفاده می‌کنیم")

    need_release = mode == "release" or (mode == "both") or (mode == "telegram" and not sent_via_telegram)
    if need_release:
        rel = GitHubRelease().publish_video(
            video_path, title=f"{channel_name} — {topic}",
            body=f"Auto-generated by YouTube-Automation-Factory.\nChannel: {channel_name}\nTopic: {topic}",
        )
        if rel.get("ok"):
            lines.append(f"🔗 لینک دانلود: {rel['url']}")
        else:
            lines.append(f"⚠️ آپلود Release ناموفق: {rel.get('error')}")

    return "\n".join(lines) if lines else "⚠️ هیچ روش تحویلی تنظیم نشده"


def run_factory():
    print("=" * 60)
    print("🏭 YOUTUBE AUTOMATION FACTORY — REAL PIPELINE 🏭")
    print("=" * 60)

    channels = load_channels()
    if not channels:
        print("⚠️  No channels registered. Nothing to do.")
        return

    only_channel = os.environ.get("ONLY_CHANNEL", "").strip()
    if only_channel:
        channels = [c for c in channels if c["id"] == only_channel]
        if not channels:
            print(f"❌ Channel '{only_channel}' not found in {_DB_PATH}.")
            return

    skip_upload = os.environ.get("SKIP_UPLOAD") == "1"
    target_minutes = int(os.environ.get("TARGET_MINUTES", "8"))
    deliver_mode = os.environ.get("DELIVER_MODE", "both")

    analyzer = NicheAnalyzer()
    factory = VideoFactory()
    publisher = AutoPublisher()
    perf = PerformanceAnalyzer()

    for ch in channels:
        if not ch.get("active", True):
            print(f"\n⏸️  Skipping inactive channel: {ch['name']}")
            continue

        print(f"\n📺 Processing Channel: {ch['name']} (niche: {ch['niche_key']}, lang: {ch['language']})")
        print("-" * 50)

        topic = analyzer.analyze_market(ch["niche_key"])
        video_result = factory.build_video(topic, ch, target_minutes=target_minutes)

        if video_result.get("error"):
            print(f"❌ Video build failed for {ch['name']}: {video_result['error']}")
            telegram_notify.send(f"❌ ساخت ویدیو برای کانال «{ch['name']}» شکست خورد:\n{video_result['error']}")
            continue

        print(f"✅ Video built: {video_result['video_path']} "
              f"({video_result['duration']:.1f}s, {video_result['scenes_rendered']} scenes)")

        deliver_summary = _deliver_video(video_result["video_path"], ch["name"], topic, deliver_mode)

        upload_line = ""
        if not skip_upload:
            metadata = publisher.generate_metadata(topic, ch.get("niche_label", ""), ch["language"])
            upload_result = publisher.upload_to_youtube(ch, video_result["video_path"], metadata)
            if upload_result.get("error"):
                print(f"⚠️  Upload skipped/failed for {ch['name']}: {upload_result['error']}")
                upload_line = f"\n⚠️ آپلود خودکار یوتیوب: {upload_result['error']}"
            else:
                perf.log_upload(ch["id"], topic, upload_result["video_id"], upload_result["url"])
                print(f"🎉 Channel {ch['name']} updated successfully! {upload_result['url']}")
                upload_line = f"\n📺 آپلود شد روی یوتیوب: {upload_result['url']}"
        else:
            upload_line = "\n⏭️ SKIP_UPLOAD=1 — روی یوتیوب آپلود نشد (فقط تست ساخت)"

        telegram_notify.send(
            f"✅ *ویدیوی جدید ساخته شد!*\n\n"
            f"📺 کانال: {ch['name']}\n"
            f"📝 موضوع: {topic}\n"
            f"⏱ مدت: {video_result['duration']:.0f} ثانیه\n\n"
            f"{deliver_summary}{upload_line}"
        )


if __name__ == "__main__":
    os.makedirs("output", exist_ok=True)
    run_factory()
