#!/usr/bin/env python3
"""Master Controller (The CEO) — real pipeline, no mocks.

Loops through every active channel in channels/database.json, finds a real
trending topic, builds a real narrated+subtitled video from free stock
footage (informed by a competitor/high-view-pattern analysis), generates a
thumbnail and 2-3 Shorts clips, and uploads everything to the real YouTube
channel via OAuth2.

Env vars:
  SKIP_UPLOAD=1          Build videos without uploading to YouTube (testing).
  TARGET_MINUTES=8       Narration length target per video.
  MAKE_SHORTS=1          Auto-generate 2-3 vertical Shorts per video (default on).
  ONLY_CHANNEL=<id>      Process just this one channel (used by the
                         Telegram bot's "make a video now" / "test channel"
                         commands so the user doesn't have to wait for
                         every channel to render before seeing a result).
  DELIVER_MODE=telegram|release|both   How to hand the finished MP4 to the
                         user (default: both — Telegram if it fits under
                         the Bot API's ~50MB upload limit, else a GitHub
                         Release download link; 'both' tries Telegram first
                         and always ALSO publishes a Release link as a
                         permanent backup/archive).
"""

import os
import json
import sys

from core.niche_analyzer import NicheAnalyzer
from core.video_factory import VideoFactory
from core.auto_publisher import AutoPublisher
from core.performance_analyzer import PerformanceAnalyzer
from core.gh_release import GitHubRelease
from core import telegram_notify
from core import schedule_guard
from core import channel_memory
from core import video_qa
from core.comment_engager import CommentEngager

_DB_PATH = "channels/database.json"
_TELEGRAM_FILE_LIMIT = 49 * 1024 * 1024  # Bot API hard cap is 50MB; stay safely under it


def load_channels() -> list:
    if not os.path.exists(_DB_PATH):
        print(f"❌ {_DB_PATH} not found. Run core/channel_spawner.py first to register a channel.")
        return []
    with open(_DB_PATH) as f:
        return json.load(f).get("channels", [])


def _send_telegram_file(path: str, channel_name: str, caption_prefix: str, kind: str) -> bool:
    """kind: 'video' or 'photo'. Returns True if sent successfully."""
    import requests
    token = os.environ.get("TELEGRAM_BOT_TOKEN_FACTORY", "")
    chat_id = telegram_notify._chat_id()
    if not (token and chat_id and os.path.exists(path)):
        return False
    method = "sendVideo" if kind == "video" else "sendPhoto"
    field = "video" if kind == "video" else "photo"
    try:
        with open(path, "rb") as f:
            r = requests.post(
                f"https://api.telegram.org/bot{token}/{method}",
                data={"chat_id": chat_id, "caption": f"{caption_prefix} {channel_name}"[:1000]},
                files={field: f},
                timeout=180,
            )
        return bool(r.json().get("ok"))
    except Exception as e:
        print(f"[deliver] Telegram {method} error: {e}")
        return False


def _deliver_video(video_path: str, channel_name: str, topic: str, mode: str) -> str:
    """Sends/uploads the finished video per DELIVER_MODE and returns a
    human-readable string describing where to find it (used in the Telegram
    summary message and the console log)."""
    size = os.path.getsize(video_path) if os.path.exists(video_path) else 0
    lines = []

    sent_via_telegram = False
    if mode in ("telegram", "both") and size and size <= _TELEGRAM_FILE_LIMIT:
        if _send_telegram_file(video_path, channel_name, "🎬", "video"):
            sent_via_telegram = True
            lines.append("📲 مستقیم توی تلگرام ارسال شد")
        else:
            print("[deliver] Telegram sendVideo failed or not configured")
    elif mode in ("telegram", "both") and size > _TELEGRAM_FILE_LIMIT:
        lines.append(f"📦 حجم فایل ({size / 1e6:.0f}MB) برای تلگرام زیاده — از لینک گیت‌هاب استفاده می‌کنیم")

    need_release = mode == "release" or (mode == "both") or (mode == "telegram" and not sent_via_telegram)
    if need_release:
        rel = GitHubRelease().publish_video(
            video_path, title=f"{channel_name} — {topic}",
            body=f"Auto-generated by YouTube-Automation-Factory.\nChannel: {channel_name}\nTopic: {topic}",
        )
        if rel.get("ok"):
            lines.append(f"🔗 لینک دانلود: {rel['url']}")
        else:
            lines.append(f"⚠️ آپلود Release ناموفق: {rel.get('error')}")

    return "\n".join(lines) if lines else "⚠️ هیچ روش تحویلی تنظیم نشده"


def run_factory():
    print("=" * 60)
    print("🏭 YOUTUBE AUTOMATION FACTORY — REAL PIPELINE 🏭")
    print("=" * 60)

    channels = load_channels()
    if not channels:
        print("⚠️  No channels registered. Nothing to do.")
        return

    only_channel = os.environ.get("ONLY_CHANNEL", "").strip()
    if only_channel:
        channels = [c for c in channels if c["id"] == only_channel]
        if not channels:
            print(f"❌ Channel '{only_channel}' not found in {_DB_PATH}.")
            return

    skip_upload = os.environ.get("SKIP_UPLOAD") == "1"
    target_minutes = int(os.environ.get("TARGET_MINUTES", "8"))
    deliver_mode = os.environ.get("DELIVER_MODE", "both")
    make_shorts = os.environ.get("MAKE_SHORTS", "1") == "1"

    analyzer = NicheAnalyzer()
    factory = VideoFactory()
    publisher = AutoPublisher()
    perf = PerformanceAnalyzer()

    for ch in channels:
        if not ch.get("active", True):
            print(f"\n⏸️  Skipping inactive channel: {ch['name']}")
            continue

        upload_frequency = ch.get("upload_frequency", "weekly")
        # BUG FIX (2026-07-04): upload_frequency was accepted at channel
        # registration but never actually enforced -- every active channel
        # got a brand new video (full LLM script + render + Shorts) EVERY
        # day regardless of this setting, silently multiplying token/render
        # cost. only_channel (explicit /testvideo or /makevideo from the
        # bot) always bypasses this check -- a manual request should always
        # run immediately.
        if not only_channel and not schedule_guard.is_due(ch["id"], upload_frequency):
            days_left = -schedule_guard.days_until_due(ch["id"], upload_frequency)
            print(f"\n⏭️  Skipping {ch['name']}: not due yet per upload_frequency="
                  f"'{upload_frequency}' ({days_left:.1f} days remaining)")
            continue

        print(f"\n📺 Processing Channel: {ch['name']} (niche: {ch['niche_key']}, lang: {ch['language']})")
        print("-" * 50)

        topic = analyzer.analyze_market(ch["niche_key"], channel_id=ch["id"], language=ch["language"])

        # RETRY LOOP (2026-07-05, explicit follow-up to the QA agent): before
        # this, a video whose narration failed the post-render coherence
        # check was simply abandoned -- an alert was sent and the pipeline
        # moved on, wasting the whole render and leaving the channel with no
        # video at all that day. A garbled LLM script can't be known bad
        # until it's actually rendered and transcribed (that's the whole
        # point of doing real audio QA instead of just trusting "the LLM
        # call succeeded"), so on a narration-coherence failure specifically,
        # retry ONCE with force_content_bank=True -- skip the unreliable LLM
        # path entirely and use a verified-coherent curated script instead of
        # repeating the same failure. A loudness failure is NOT retried here:
        # it indicates a systemic render/mixing bug (like the amix
        # normalize=1 issue found earlier), not a random per-attempt fluke,
        # so retrying identically would just fail identically -- that case
        # still goes straight to a user alert for manual investigation.
        max_attempts = 2
        video_result, qa_report = None, None
        for attempt in range(1, max_attempts + 1):
            force_content_bank = attempt > 1
            if force_content_bank:
                print(f"[Retry {attempt}/{max_attempts}] Narration QA failed last attempt -- "
                      f"retrying '{ch['name']}' with a verified-coherent content_bank script "
                      f"instead of the LLM.")
            video_result = factory.build_video(
                topic, ch, target_minutes=target_minutes, make_shorts=make_shorts,
                force_content_bank=force_content_bank,
            )
            if video_result.get("error"):
                break  # a build error isn't something a content_bank retry can fix

            attempt_topic = video_result.get("topic", topic)
            qa_report = video_qa.run_qa(
                video_result["video_path"], video_result.get("full_narration_text", ""),
                language=ch["language"],
            )
            if qa_report.get("ok"):
                break

            narration_check = qa_report.get("narration_check", {})
            narration_failed = narration_check and not narration_check.get("ok", True)
            loudness_failed = not qa_report.get("audio_loudness", {}).get("ok", True)
            if loudness_failed or not narration_failed or attempt >= max_attempts:
                break  # nothing left to retry, or this failure mode can't be fixed by retrying
            print(f"⚠️  QA rejected attempt {attempt} for {ch['name']}: narration overlap "
                  f"{narration_check.get('overlap_ratio')} -- will retry.")

        # Mark the schedule as consumed regardless of success/failure -- a
        # failed attempt still spent real LLM/API calls, so a broken
        # channel shouldn't retry every single day and multiply that cost.
        if not only_channel:
            schedule_guard.mark_run(ch["id"])

        if video_result.get("error"):
            print(f"❌ Video build failed for {ch['name']}: {video_result['error']}")
            telegram_notify.send(f"❌ ساخت ویدیو برای کانال «{ch['name']}» شکست خورد:\n{video_result['error']}")
            continue

        print(f"✅ Video built: {video_result['video_path']} "
              f"({video_result['duration']:.1f}s, {video_result['scenes_rendered']} scenes)")

        # VideoFactory/ScriptWriter may have SUBSTITUTED the topic (see
        # core/content_bank.py's random_topic_for_niche -- happens when the
        # topic NicheAnalyzer picked has no curated script AND every LLM
        # failed). Use the ACTUAL topic that was narrated for everything
        # downstream: delivery caption, YouTube title/description, memory.
        topic = video_result.get("topic", topic)

        # REAL QA PASS (explicit user request 2026-07-05: "قبل از اینکه
        # ویدیو رو برام بفرسته خودش ویدیو رو چک کنه" -- "before sending me
        # the video, [the agent] should check it itself"). Actually measures
        # the finished video's audio loudness (catches the ffmpeg amix
        # normalize=1 bug class -- narration silently mixed too quiet to
        # hear under music) and, for Persian, transcribes the narration with
        # openai-whisper and compares it against the source script (catches
        # a garbled/incoherent LLM-written script slipping through, which is
        # exactly what happened with a free OpenRouter model in a real test
        # video). A video that fails is NOT silently delivered -- the user
        # is alerted instead, with the specific reason, so a broken video
        # never just "goes out" unnoticed again.
        print(f"[QA] Running automated checks (audio loudness"
              f"{', Persian narration transcription' if ch['language'] == 'fa' else ''}) before delivery...")
        qa_report = video_qa.run_qa(
            video_result["video_path"], video_result.get("full_narration_text", ""),
            language=ch["language"],
        )
        if not qa_report.get("ok"):
            print(f"⚠️  QA FAILED for {ch['name']}: {qa_report}")
            qa_lines = []
            loudness = qa_report.get("audio_loudness", {})
            if not loudness.get("ok", True):
                qa_lines.append(f"🔇 صدای روایت خیلی کمه (mean_volume={loudness.get('mean_volume_db')} dB)")
            narration_check = qa_report.get("narration_check", {})
            if not narration_check.get("ok", True):
                qa_lines.append(
                    f"🗣 متن روایت‌شده با اسکریپت اصلی همخوانی کافی نداره "
                    f"(تطابق: {narration_check.get('overlap_ratio', 0)*100:.0f}٪) -- "
                    f"رونوشت واقعی: «{narration_check.get('transcript', '')[:200]}»"
                )
            telegram_notify.send(
                f"⚠️ *ویدیوی «{ch['name']}» ساخته شد ولی در بررسی کیفیت خودکار رد شد -- ارسال نشد.*\n\n"
                f"موضوع: {topic}\n\n" + "\n".join(qa_lines) +
                f"\n\nاین ویدیو نیاز به بررسی دستی یا ساخت مجدد داره."
            )
            continue
        print(f"[QA] Passed. mean_volume={qa_report.get('audio_loudness', {}).get('mean_volume_db')} dB"
              + (f", narration_overlap={qa_report.get('narration_check', {}).get('overlap_ratio')}"
                 if "narration_check" in qa_report else ""))

        thumbnail_path = video_result.get("thumbnail_path", "")
        shorts = video_result.get("shorts", [])

        deliver_summary = _deliver_video(video_result["video_path"], ch["name"], topic, deliver_mode)

        # Thumbnail preview: always sent via Telegram when possible (tiny file)
        if thumbnail_path and os.path.exists(thumbnail_path):
            _send_telegram_file(thumbnail_path, ch["name"], "🖼 تامبنیل", "photo")

        # Shorts: sent via Telegram if small enough, else linked via Release
        shorts_lines = []
        for i, short in enumerate(shorts, 1):
            short_size = os.path.getsize(short["path"]) if os.path.exists(short["path"]) else 0
            if short_size and short_size <= _TELEGRAM_FILE_LIMIT:
                if _send_telegram_file(short["path"], ch["name"], f"🎞 Short {i}:", "video"):
                    shorts_lines.append(f"🎞 Short {i}: ارسال شد در تلگرام")
                    continue
            rel = GitHubRelease().publish_video(
                short["path"], title=f"{ch['name']} Short {i} — {topic}",
                body=f"Auto-generated Short clip.\nChannel: {ch['name']}\nTopic: {topic}",
            )
            if rel.get("ok"):
                shorts_lines.append(f"🎞 Short {i}: {rel['url']}")

        upload_line = ""
        if not skip_upload:
            metadata = publisher.generate_metadata(
                topic, ch.get("niche_label", ""), ch["language"],
                comment_prompt=video_result.get("outro_text", ""),
                music_credit=video_result.get("music_credit", ""),
            )
            upload_result = publisher.upload_to_youtube(
                ch, video_result["video_path"], metadata, thumbnail_path=thumbnail_path
            )
            if upload_result.get("error"):
                print(f"⚠️  Upload skipped/failed for {ch['name']}: {upload_result['error']}")
                upload_line = f"\n⚠️ آپلود خودکار یوتیوب: {upload_result['error']}"
            else:
                perf.log_upload(ch["id"], topic, upload_result["video_id"], upload_result["url"])
                # Backfill the memory record for this topic with the real
                # video_id/url now that upload succeeded (record_video()
                # matches by topic and updates in place instead of duplicating).
                channel_memory.record_video(
                    ch["id"], topic, metadata.get("title", topic), video_result["video_path"],
                    [], video_result["script_engine"],
                    video_id=upload_result["video_id"], video_url=upload_result["url"],
                )
                # Reply to any early comments right away -- comments in the
                # first 1-2 hours matter most for the algorithm's early
                # reach signal (see docs/YOUTUBE-GROWTH-AND-ENGAGEMENT.md).
                # This is a best-effort attempt immediately after upload;
                # ENGAGE-COMMENTS.yml (a separate scheduled workflow) covers
                # comments that arrive later.
                service = publisher.build_service(ch)
                if service is not None:
                    engage_result = CommentEngager().reply_to_new_comments(
                        service, upload_result["video_id"], topic, ch["language"]
                    )
                    if engage_result.get("replied"):
                        print(f"[CommentEngager] Replied to {len(engage_result['replied'])} "
                              f"early comment(s) on {upload_result['video_id']}")
                print(f"🎉 Channel {ch['name']} updated successfully! {upload_result['url']}")
                upload_line = f"\n📺 آپلود شد روی یوتیوب: {upload_result['url']}"
                if upload_result.get("thumbnail_warning"):
                    upload_line += f"\n⚠️ تامبنیل ست نشد: {upload_result['thumbnail_warning']}"
        else:
            upload_line = "\n⏭️ SKIP_UPLOAD=1 — روی یوتیوب آپلود نشد (فقط تست ساخت)"

        shorts_block = ("\n\n" + "\n".join(shorts_lines)) if shorts_lines else ""

        telegram_notify.send(
            f"✅ *ویدیوی جدید ساخته شد!*\n\n"
            f"📺 کانال: {ch['name']}\n"
            f"📝 موضوع: {topic}\n"
            f"⏱ مدت: {video_result['duration']:.0f} ثانیه\n\n"
            f"{deliver_summary}{shorts_block}{upload_line}"
        )


if __name__ == "__main__":
    os.makedirs("output", exist_ok=True)
    run_factory()
