"""VideoQA — a real quality-assurance pass that actually LISTENS to and
LOOKS at a finished video before it gets sent to the user, instead of the
agent only spot-checking a few extracted frames by eye (which is what
happened in earlier sessions and is exactly what the user called out:
"تو خودت ویدیو رو بررسی کردی؟" -- "did YOU actually check the video?").

WHY THIS EXISTS: two real, confirmed bugs shipped in test videos that pure
frame-checking never would have caught:
  1. Narration audio was ~6dB quieter than intended because of ffmpeg's
     amix normalize=1 default (see core/video_assembler.py's fix) -- only
     detectable by actually measuring the mixed audio's loudness.
  2. A Persian script generated by a free OpenRouter model came out
     partially incoherent/garbled -- only detectable by actually
     transcribing the narration audio and checking it resembles the
     source script, not just checking the LLM call "succeeded".

This module runs BOTH checks on every real render, using tools that are
free and already installed in the pipeline environment (openai-whisper for
speech-to-text, ffmpeg's volumedetect for loudness) -- no paid API calls,
no extra cost.

Returns a report the caller (main.py) uses to decide whether to actually
deliver a video or hold it back and alert the user instead of silently
shipping a broken one.
"""

import os
import re
import subprocess

from . import script_quality

# --------------------------------------------------------------------- #
# 1. AUDIO LOUDNESS CHECK -- catches the amix normalize=1 bug class (any
#    future filter_complex regression that silently halves narration
#    volume) without needing to listen to every render by ear.
# --------------------------------------------------------------------- #
_MIN_MEAN_VOLUME_DB = -30.0  # quieter than this and narration is likely
                             # inaudible/hard to hear over background music


def check_audio_loudness(video_path: str) -> dict:
    """Runs ffmpeg's volumedetect filter on the final muxed audio track and
    returns {'ok': bool, 'mean_volume_db': float, 'max_volume_db': float}
    (or {'ok': False, 'error': ...} if ffmpeg/ffprobe aren't available or
    the file has no audio track)."""
    try:
        result = subprocess.run(
            ["ffmpeg", "-i", video_path, "-af", "volumedetect", "-f", "null", "-"],
            capture_output=True, text=True, timeout=120,
        )
        stderr = result.stderr
        mean_match = re.search(r"mean_volume:\s*(-?\d+\.?\d*)\s*dB", stderr)
        max_match = re.search(r"max_volume:\s*(-?\d+\.?\d*)\s*dB", stderr)
        if not mean_match:
            return {"ok": False, "error": "volumedetect_produced_no_output"}
        mean_db = float(mean_match.group(1))
        max_db = float(max_match.group(1)) if max_match else None
        return {
            "ok": mean_db >= _MIN_MEAN_VOLUME_DB,
            "mean_volume_db": mean_db,
            "max_volume_db": max_db,
        }
    except (subprocess.TimeoutExpired, FileNotFoundError, ValueError) as e:
        return {"ok": False, "error": str(e)}


# --------------------------------------------------------------------- #
# 2. NARRATION COHERENCE CHECK -- actually transcribes the finished
#    video's audio (openai-whisper, runs locally, no API cost) and
#    compares it against the source script text, instead of just trusting
#    that "the LLM call succeeded" or "the TTS call succeeded" means the
#    result is understandable.
# --------------------------------------------------------------------- #
_MIN_WORD_OVERLAP_RATIO = 0.35  # how much of the source script's vocabulary
                                # must show up in the transcript for the
                                # narration to be considered "matches the
                                # script" rather than badly mispronounced/
                                # garbled beyond recognition


_PERSIAN_ARABIC_PUNCTUATION = "،؛؟٫٬٪۔ـ"


def _normalize_words(text: str) -> set:
    # BUG FIXED (found by re-testing this exact module against the agent's
    # OWN known-good, hand-written content_bank.py script -- it failed the
    # overlap check too, which meant the check itself was broken, not the
    # narration). Root cause: Persian/Arabic punctuation marks (، ؛ ؟ etc.)
    # live INSIDE the same 0600-06FF Unicode block as Persian letters, so
    # the old regex kept them attached to words (e.g. "سال،" with a
    # trailing Arabic comma), which then never matched Whisper's cleaner
    # "سال" -- an artificial mismatch that had nothing to do with actual
    # narration coherence. Strip Persian/Arabic punctuation explicitly
    # before extracting words.
    cleaned = text.replace("\u200c", " ")
    for ch in _PERSIAN_ARABIC_PUNCTUATION:
        cleaned = cleaned.replace(ch, " ")
    words = re.findall(r"[\u0600-\u06FFa-zA-Z]+", cleaned.lower())
    return {w for w in words if len(w) > 2}


def transcribe_and_compare(video_path: str, source_text: str, language: str = "fa",
                            whisper_model_size: str = "base") -> dict:
    """Transcribes the video's audio with openai-whisper and compares the
    resulting word set against the source narration script. Returns
    {'ok': bool, 'overlap_ratio': float, 'transcript': str} or
    {'ok': False, 'error': ...} if whisper isn't installed/fails (never
    raises -- a missing optional QA dependency should degrade to "QA
    skipped", not crash the pipeline).

    NOTE on expected transcript quality: Whisper (even at larger model
    sizes) does not perfectly transcribe TTS-synthesized Persian speech --
    proper nouns, numbers-as-words, and rare terms are commonly
    mistranscribed even for GOOD narration. This check is deliberately
    calibrated to catch GROSS incoherence (wrong language mixed in,
    completely different content, a badly broken TTS run) rather than to
    demand a perfect transcript match, which even a real human narrator's
    recording would not achieve against automatic transcription."""
    try:
        import whisper
    except ImportError:
        return {"ok": True, "skipped": "openai-whisper not installed"}

    try:
        model = whisper.load_model(whisper_model_size)
        result = model.transcribe(video_path, language=language)
        transcript = result.get("text", "")
    except Exception as e:
        return {"ok": True, "skipped": f"transcription_failed: {e}"}

    source_words = _normalize_words(source_text)
    transcript_words = _normalize_words(transcript)
    if not source_words:
        return {"ok": True, "skipped": "empty_source_text"}

    overlap = len(source_words & transcript_words)
    ratio = overlap / len(source_words)
    return {
        "ok": ratio >= _MIN_WORD_OVERLAP_RATIO,
        "overlap_ratio": round(ratio, 3),
        "transcript": transcript.strip(),
    }


# --------------------------------------------------------------------- #
def run_qa(video_path: str, full_narration_text: str, language: str = "en",
           run_transcription_check: bool = True) -> dict:
    """Full QA pass on one finished video. Returns:
    {
      'ok': bool,              -- overall pass/fail
      'audio_loudness': {...}, -- see check_audio_loudness
      'narration_check': {...} -- see transcribe_and_compare (only if
                                   run_transcription_check and language=='fa',
                                   since that's the confirmed real failure
                                   mode; skipped for other languages to
                                   avoid unnecessary render time)
    }
    A video that fails QA should NOT be silently delivered -- main.py uses
    this to decide whether to alert the user instead of shipping a broken
    result (this whole module exists because the user explicitly asked for
    exactly that: "قبل از اینکه ویدیو رو برام بفرسته خودش ویدیو رو چک کنه").
    """
    if not os.path.exists(video_path):
        return {"ok": False, "error": "video_file_missing"}

    report = {"ok": True}

    loudness = check_audio_loudness(video_path)
    report["audio_loudness"] = loudness
    if not loudness.get("ok", True):
        report["ok"] = False

    if run_transcription_check and language == "fa":
        narration_check = transcribe_and_compare(video_path, full_narration_text, language=language)
        report["narration_check"] = narration_check
        if not narration_check.get("ok", True):
            report["ok"] = False

    return report


if __name__ == "__main__":
    import json
    import sys

    if len(sys.argv) < 2:
        print("Usage: python -m core.video_qa <video_path> [narration_text] [language]")
        sys.exit(1)
    path = sys.argv[1]
    text = sys.argv[2] if len(sys.argv) > 2 else ""
    lang = sys.argv[3] if len(sys.argv) > 3 else "en"
    print(json.dumps(run_qa(path, text, lang), indent=2, ensure_ascii=False))
